package app.cash.zipline.bridge.support

/**
 * Marker annotation for classes whose JNI bridge code should be generated by the Zipline bridge
 * Kotlin compiler plugin.
 *
 * @param targetFqn Optional fully qualified name of the JVM class to instantiate in generated
 *   C code. When empty, the annotated class's own FQN is used. Set this when the JS-side class
 *   and JVM-side class live in different packages (e.g. compose-side vs protocol-host Impls).
 */
@Retention(AnnotationRetention.BINARY)
@Target(AnnotationTarget.CLASS)
public annotation class WithJS2HostBridge(
  val targetFqn: String = "",
)
